# Generated by Django 4.0.3 on 2022-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Phone1_Type', models.CharField(max_length=20)),
                ('phone1_value', models.CharField(max_length=10)),
            ],
        ),
    ]
