# Generated by Django 4.0.3 on 2022-03-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CsvUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
