# Generated by Django 4.0.3 on 2022-03-29 06:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CsvUpload', '0003_alter_uploadcsv_phone1_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='phone1_value',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
